galaxy_info:
  author: nginxinc
  description: Example Ansible role for installing NGINX Developer Portal
  role_name: nginx_devportal
  company: F5, Inc.

  license: Apache License, Version 2.0

  min_ansible_version: '2.10'

  platforms:
    - name: Ubuntu
      versions: [focal]

  galaxy_tags: []

dependencies: []
